env: none

#全局的ribbon设置
# feign.RetryableException: Read timed out executing POST
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
