env: test
eureka:
  instance:
    metadataMap:
      tag: offline
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.1.56:1111/eureka/
      loadbalancer:
        retry:
          enabled: false

spring:
  cache:
    type: redis
    cache-names: redisCache
  redis:
    database: 1
    host: 192.168.1.56
    timeout: 0
    password: ss541018
    sentinel:
      master: mymaster
      nodes: 192.168.1.56:26379,192.168.1.56:26378,192.168.1.56:26377


zuul:
  routes:
    product: /myProduct/**
  host:
    connect-timeout-millis: 10000
#  servlet-path: api